# Generated by Django 5.1.3 on 2024-11-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_name_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='category',
            new_name='categoria',
        ),
    ]
