# Generated by Django 5.2 on 2025-06-13 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_categoria_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('user_add', 'Usuario creado'), ('user_del', 'Usuario eliminado'), ('prod_add', 'Producto creado'), ('prod_edit', 'Producto editado'), ('prod_del', 'Producto eliminado'), ('cat_add', 'Categoría creada'), ('cat_edit', 'Categoría editada'), ('cat_del', 'Categoría eliminada'), ('order_add', 'Pedido creado'), ('order_edit', 'Pedido editado'), ('order_del', 'Pedido eliminado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
