# Generated by Django 5.2 on 2025-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
