# Generated by Django 5.2 on 2025-10-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_pedido_entrega_estimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('user_add', 'Usuario creado'), ('user_del', 'Usuario eliminado'), ('prod_add', 'Producto creado'), ('prod_edit', 'Producto editado'), ('prod_del', 'Producto eliminado'), ('cat_add', 'Categoría creada'), ('cat_edit', 'Categoría editada'), ('cat_del', 'Categoría eliminada'), ('order_add', 'Pedido creado'), ('order_edit', 'Pedido editado'), ('order_del', 'Pedido eliminado'), ('order_accept', 'Pedido aceptado')], max_length=20),
        ),
    ]
