# Generated by Django 5.2 on 2025-05-24 01:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
